### ISSUE TITLE
Like Swipe action does not update UI

### ISSUE THREAD

**Issue by j-r-moore** [BLeeEZ/amperfy#354] opened 2024-11-22 22:14 UTC
Minor bug. When using “like song” with swipe function on songs the heart icon doesn’t appear until you reopen the songs list

**Comment by Schlaubischlump** [comment] 2024-12-05 23:11
I can confirm this bug. Right click to mark as favorite does also not work. 

For some reason `controller(_:didChange:at:for:newIndexPath:)` is never called when a song is marked as favorite.

**Comment by BLeeEZ** [comment] 2024-12-06 08:02
I think I found the root cause.
Swipe and right click should correctly update the heart in the Album detail view (songs of an album).
In this view I am using a DiffableDataSource. In the other views I am still using the UITableViewController callbacks.
I think it is necessary to refactor the existing table views to use the DiffableDataSource.

**Comment by Schlaubischlump** [comment] 2024-12-06 14:08
Maybe that will also fix the problem. I don't know this part of the codebase well enough. However, `ArtistVC` also uses the old tableView API. I can mark artists as favorites without any problems. The reason for that is, that `ArtistFetchedResultsController` does not change the default `true` value of `keepAllResultsUpdated`. 

If I change `SongsFetchedResultsController` to not set `keepAllResultsUpdated` to `false`, everything is working as expected. This is consistent with the behavior I observed in my last message, since all this flag does is settings the delegate of `NSFetchedResultsController`. 

Is there a particular reason (performance?) why this flag is `false` only for the `SongsFetchedResultsController`? If not, I would propose to change this flag to `true` and close this issue.

**Comment by BLeeEZ** [comment] 2024-12-06 20:10
The `keepAllResultsUpdated` reduces the CPU load for Songs view controller. During background album's songs sync the songs view is basically unusable, because every synced song results in an SongVC update. I fixed the refresh directly in the swipe and preview class. This fixes the favourite and cache icon for macOS player playlist sideview and PopupPlayer playlist too: 19bd6c97e17e929fdd4c81883a5eecd7583af406

**Closed** 2024-12-06 20:28 UTC
Labels: bug, implemented
