### ISSUE TITLE
Encoding and date on podcast wrong display (French)

### ISSUE THREAD

**Issue by YasserAntonio** [BLeeEZ/amperfy#80] opened 2021-12-02 13:38 UTC
the podcast works well but don't shows up the content as it should.
i have find errors on the displayed date (always on 1 January as on screenshot) and badly interpreted chars (é in the title but not in the description)  / html ( bold tags like <br> etc..) rendering on the French podcast  https://podcast.ausha.co/les-actus-du-jour

![IMG_00EDE5358120-1](https://user-images.githubusercontent.com/8104486/144432207-f68b42a0-41ef-4461-9421-fcd1f9e06cdb.jpeg)

**Comment by BLeeEZ** [comment] 2021-12-02 18:55
1. Publish dates: With the latest Ampache version the published date format changed from "3/27/21, 3:30 AM" to "2011-02-03T14:46:43". This issue is already fixed with this commit: 12f66d400e85f0ba8ec1b0636604cecc8feee903
2. Episode description: I can reproduce the issue. I will take a look at it.

**Comment by BLeeEZ** [comment] 2021-12-03 20:17
The issue is fixed with this commit: 67f5782046b3b21b4c3904e62e19dbe1c169124
![Simulator Screen Shot - iPhone 11 Pro - 2021-12-03 at 20 21 20](https://user-images.githubusercontent.com/17556018/144667308-ad23e6f0-d079-46de-922b-939a0929ef06.png)
9

**Comment by YasserAntonio** [comment] 2021-12-03 21:39
Thanks !

**Closed** 2022-01-03 19:52 UTC
