### ISSUE TITLE
[Bug]: Queuing doesn’t by swiping doesn’t always trigger

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#82] opened 2022-01-03 16:20 UTC
When you don't swipe far enough the song isn't queued, the video below should make clear what I mean by this:
https://user-images.githubusercontent.com/21057514/147954206-46641ab4-145a-494f-8d2c-885a0bc04f54.MOV

EDIT: I just noticed I accidentally recorded the audio I was playing in the screen recording too, just so you know.

**Comment by BLeeEZ** [comment] 2022-01-03 19:55
This is the default behavior defined by Apple.
My function to queue the song is only called if the element is completely swiped to the right or the swipe started and then the playlist icon is pressed.

**Comment by sandersantema** [comment] 2022-01-03 20:09
It's probably not clear from the recording (blame the lack of a cursor function for that) but at 0:05 seconds I've released my finger from the screen and the swipe thing gets stuck. I think that is still a bug given that I've not noticed it happening in other apps and can't get it to trigger in other apps either.

**Comment by BLeeEZ** [comment] 2022-01-04 09:08
This is intended behavior. Apples email client on iOS works the same way.
If you swipe an already read email to the right it will be marked as unread.

When you swipe the complete distance from left to right -> the playlist icon will moves to the right and a light vibration occurs. Or you slightly swipe to the right then the icon will stay there and you can trigger it by tapping on the icon.

**Comment by sandersantema** [comment] 2022-01-04 15:54
Well that's interesting :thinking: not the best default behavior I would say. But I think it is more important to increase the stability of the app further and flesh out some features than this visual feedback (if it requires third party libraries and therefore I assume quite a lot more work). So IMHO I think this should be put on the backburner, there's more important stuff and the functionality is working as expected. The lack of visual feedback is probably something you won't even notice if you've used it for a while.

**Comment by sandersantema** [comment] 2022-01-04 15:57
Well that's interesting :thinking: not the best default behavior I would say. But like #84 something which can be done later if you want to change it at all. If you agree might it be nice to add a label to this issue and #84? If you don't already have one I've seen the label`backlog` used before.

**Comment by BLeeEZ** [comment] 2022-08-20 06:30
I will track this under feature request #84 .

**Closed by BLeeEZ** 2022-08-20 06:30 UTC
Labels: enhancement
