### ISSUE TITLE
Unable to play music after syncing

### ISSUE THREAD

**Issue by ccp-codex** [BLeeEZ/amperfy#5] opened 2019-06-08 17:14 UTC
After successfully connecting to an ampache endpoint and syncing my library, when I attempt to play a song in m4a or mp3 format the progress bar fails to move beyond 0:00

This result is the same whether running in an iOS simulator or on my iOS device.

`2019-06-08 17:10:52.534701+0000 Amperfy[2454:646954] Error Player: The operation couldn’t be completed. (OSStatus error -50.)
2019-06-08 17:10:59.956367+0000 Amperfy[2454:646954] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-06-08 17:10:59.958217+0000 Amperfy[2454:646954] [MC] Reading from public effective user settings.
2019-06-08 17:12:55.275214+0000 Amperfy[2454:646954] [Ampache] https://cloud.redshift.is/apps/music/ampache/server/xml.server.php?action=handshake&auth=9a45f4e915282c05887dcc005d3008f35a73cf6115bfd69fce04108ccf27507a&timestamp=1560013975&version=350001&user=ncp
2019-06-08 17:12:55.696373+0000 Amperfy[2454:646954] [BackendProxy] Ampache is active backend api
2019-06-08 17:12:56.251650+0000 Amperfy[2454:646954] [BackgroundSyncer] SyncInBackground stopped
2019-06-08 17:12:56.612037+0000 Amperfy[2454:647432] [Parser] Found album id 18 with unknown artist 35
2019-06-08 17:12:56.919351+0000 Amperfy[2454:647432] [Parser] Found song id 18 with unknown artist 35
2019-06-08 17:12:57.637359+0000 Amperfy[2454:647432] [BackgroundSyncer] SyncInBackground start
2019-06-08 17:12:57.642885+0000 Amperfy[2454:647276] [LibrarySyncer] Lib resync: No changes
2019-06-08 17:12:58.240410+0000 Amperfy[2454:647464] [LibrarySyncer] Not able to fetch img
2019-06-08 17:12:58.241501+0000 Amperfy[2454:647464] [LibrarySyncer] All artworks are synced
2019-06-08 17:13:04.811039+0000 Amperfy[2454:646954] [Snapshotting] Snapshotting a view (0x1050bec00, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
2019-06-08 17:13:06.114191+0000 Amperfy[2454:646954] [BackgroundSyncer] SyncInBackground start
2019-06-08 17:13:06.116564+0000 Amperfy[2454:647464] [LibrarySyncer] Lib resync: No changes
2019-06-08 17:13:06.741182+0000 Amperfy[2454:647645] [LibrarySyncer] All artworks are synced
2019-06-08 17:13:11.563333+0000 Amperfy[2454:647647] [DownloadManager] DownloadManager start
2019-06-08 17:13:11.563543+0000 Amperfy[2454:647434] [DownloadManager] Fetching  - Agnus Dei - Samuel Barber LIVE ...
2019-06-08 17:13:12.873787+0000 Amperfy[2454:647434] [DownloadManager] Fetching  - Agnus Dei - Samuel Barber LIVE SUCCESS (6.82 MiB)
2019-06-08 17:13:12.917757+0000 Amperfy[2454:647647] [DownloadManager] DownloadManager done
2019-06-08 17:13:17.802026+0000 Amperfy[2454:647646] TIC Read Status [9:0x280c1ad00]: 1:57
2019-06-08 17:13:17.802096+0000 Amperfy[2454:647646] TIC Read Status [9:0x280c1ad00]: 1:57
2019-06-08 17:13:17.802109+0000 Amperfy[2454:647646] TIC Read Status [9:0x280c1ad00]: 1:57
2019-06-08 17:13:17.803105+0000 Amperfy[2454:647646] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C9.1:2][0x104c93260] get output frames failed, state 8196
2019-06-08 17:13:17.803177+0000 Amperfy[2454:647646] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C9.1:2][0x104c93260] get output frames failed, state 8196
2019-06-08 17:13:17.803608+0000 Amperfy[2454:647646] TIC Read Status [9:0x0]: 1:57
2019-06-08 17:13:17.803630+0000 Amperfy[2454:647646] TIC Read Status [9:0x0]: 1:57
2019-06-08 17:13:17.803642+0000 Amperfy[2454:647646] TIC Read Status [9:0x0]: 1:57
2019-06-08 17:13:17.803654+0000 Amperfy[2454:647646] TIC Read Status [9:0x0]: 1:57
`

**Comment by BLeeEZ** [comment] 2019-06-09 09:46
Thank you for your report.

Are you able to play any song via Amperfy (except songs with filetype m4a and mp3)?
Have you tried other songs?
Is a special codec or DRM required to play that song?

As much as I can see from the log is that the download of the song was successful.
I can assume two possible root causes:
1. An issue with the AVFoundation::AVPlayer playing the song.
2. After successfully downloading the song the DownloadManager will not correctly inform the player via the registered callback.

Is the "remaining time" label correctly displayed for the selected song (Full length of the song)?
-> This would remove 1. form the root cause list.

@iPrinz96 has mentioned via email a similar issue to me.
I wasn't able to reproduce the bug on my side. All songs in my library are playing.

**Comment by ccp-codex** [comment] 2019-06-09 10:38
I tried many different mp3 tracks but only 1 m4a track. Everything works fine via Power Ampache on Android and via the web-player. There's nothing special DRM-wise about the tracks but I can send you a link to one via my nextcloud instance if that would help you rule out / diagnose the issue. I'm serving the tracks via the Music app provided by the latest NextCloud release which provides an Ampache endpoint. I'm happy to set you up with a user account if you'd like to test the endpoint.

The remaining time is also 0:00 and the play button toggles to Pause but otherwise there's no additional UI feedback. 

I'm happy to help you diagnose this to whatever extent you're willing to investigate it as there are no good Ampache clients for iOS which is true shame and would really help folks like myself who want to stream their own music libraries via NextCloud and not have to maintain something like Airsonic just for that purpose.

**Comment by BLeeEZ** [comment] 2019-06-09 18:18
I have found the issue. The problem was that your song has no artist. 
I did a hard check for valid artist of a song (In my database every song has a valid artist).
Can you please check if the issue is fixed with lastest master.

**Comment by ccp-codex** [comment] 2019-06-09 21:31
Yup, that did the trick. I'll be using it pretty heavily the next week or so and will post any issues I run across. Thanks again. I hope you publish it to the app store. I'm happy to send some $ your way if you do. Thanks for fixing this!

**Closed** 2019-06-10 11:47 UTC
Labels: bug
